--添加医保2207信息 
insert into ybNew_2207_result([patient_id],
	[admiss_times],
	[mdtrt_id],
	[setl_id] ,
	[psn_no] ,
	[psn_name] ,
	[psn_cert_type],
	[certno],
	[gend],
	[naty] ,
	[brdy],
	[age] ,
	[insutype] ,
	[psn_type] ,
	[cvlserv_flag] ,
	[setl_time] ,
	[mdtrt_cert_type],
	[med_type] ,
	[medfee_sumamt],
	[fulamt_ownpay_amt] ,
	[overlmt_selfpay] ,
	[preselfpay_amt] ,
	[inscp_scp_amt] ,
	[act_pay_dedc] ,
	[hifp_pay] ,
	[pool_prop_selfpay],
	[cvlserv_pay] ,
	[hifes_pay] ,
	[hifmi_pay] ,
	[hifob_pay],
	[maf_pay] ,
	[oth_pay] ,
	[fund_pay_sumamt],
	[psn_part_amt] ,
	[acct_pay] ,
	[psn_cash_pay] ,
	[hosp_part_amt] ,
	[balc],
	[acct_mulaid_pay],
	[medins_setl_id] ,
	[clr_optins] ,
	[clr_way] ,
	[clr_type] )
values (@patient_id,
	@admiss_times,
	@mdtrt_id,
	@setl_id ,
	@psn_no,
	@psn_name ,
	@psn_cert_type,
	@certno,
	@gend,
	@naty ,
	@brdy,
	@age ,
	@insutype ,
	@psn_type ,
	@cvlserv_flag ,
	@setl_time ,
	@mdtrt_cert_type,
	@med_type ,
	@medfee_sumamt,
	@fulamt_ownpay_amt ,
	@overlmt_selfpay ,
	@preselfpay_amt,
	@inscp_scp_amt,
	@act_pay_dedc,
	@hifp_pay,
	@pool_prop_selfpay,
	@cvlserv_pay ,
	@hifes_pay ,
	@hifmi_pay ,
	@hifob_pay,
	@maf_pay ,
	@oth_pay ,
	@fund_pay_sumamt,
	@psn_part_amt ,
	@acct_pay ,
	@psn_cash_pay ,
	@hosp_part_amt ,
	@balc,
	@acct_mulaid_pay,
	@medins_setl_id ,
	@clr_optins ,
	@clr_way ,
	@clr_type )